- name: Get PostgreSQL version
  shell: psql --version  | awk -F ' ' '{print $3}'
  changed_when: no
  check_mode: no
  register: pgsql_version_check
  tags:
    - always

- name: Set PGSQL version
  set_fact:
    pgsql_version: "{{ pgsql_version_check.stdout }}"
  tags:
    - always
